In [1]:
import torch
import numpy as np

In [2]:
print(torch.cuda.is_available())

device = torch.device('cuda' if torch.cuda.is_available() else "cpu")
print(f"{device} is being used")

True
cuda is being used


### Creating Tensors
_________
**empty()** does not actually produce empty array. But generates random values. More efficient than **zeros() or ones()**

In [3]:
# Creating an empty tensor
x = torch.empty(size=(1, ))
print(x)
x = torch.empty(1)
print(x)
x = torch.empty(size=(2, 3))
print(x)

tensor([2.5223e-44])
tensor([-7333176.])
tensor([[-1.0200e+06,  3.2063e-41,  2.1174e+17],
        [ 4.5137e-41,  0.0000e+00,  0.0000e+00]])


In [4]:
# Creating Random tensors
x = torch.rand(2, 2)
print(x)
x = torch.rand(size=(2, 2))
print(x)

tensor([[0.6355, 0.1452],
        [0.9962, 0.9902]])
tensor([[0.2114, 0.5628],
        [0.8578, 0.0769]])


In [5]:
# Tensors with 0s or 1s
x = torch.zeros(size=(2, 2), dtype=torch.int32)
print(f"x = {x}, Size =  {x.size()}")
x = torch.ones(size=(2, 2))
print(x)

x = tensor([[0, 0],
        [0, 0]], dtype=torch.int32), Size =  torch.Size([2, 2])
tensor([[1., 1.],
        [1., 1.]])


In [6]:
# Creating tensor from lists
x = torch.tensor([1,2,3,4])
print(x)

tensor([1, 2, 3, 4])


### Basic Tensor Operations

In [7]:
x = torch.rand(size=(2, 2))
y = torch.rand(size=(2, 2))
z = x+y
print(z)
z = torch.add(x, y)
print(z)

tensor([[0.4318, 0.9143],
        [0.6146, 0.1978]])
tensor([[0.4318, 0.9143],
        [0.6146, 0.1978]])


In [8]:
# Using inplace addition, y's value is changed to the sum
y.add_(x)
print(y)

tensor([[0.4318, 0.9143],
        [0.6146, 0.1978]])


In [9]:
# Element-wise multiplication
z = x*y
print(z)
z = torch.mul(x, y)
print(z)

tensor([[0.1229, 0.3876],
        [0.3285, 0.0165]])
tensor([[0.1229, 0.3876],
        [0.3285, 0.0165]])


In [10]:
# Element-wise Division
z = x/y
print(z)
z = torch.div(x, y)
print(z)

tensor([[0.6592, 0.4637],
        [0.8696, 0.4207]])
tensor([[0.6592, 0.4637],
        [0.8696, 0.4207]])


### Slicing operations

In [11]:
x = torch.rand(size=(5, 3))
print(x)

tensor([[0.5073, 0.3651, 0.7974],
        [0.2781, 0.3670, 0.9745],
        [0.6344, 0.9622, 0.4619],
        [0.8707, 0.8175, 0.2129],
        [0.4571, 0.3223, 0.8074]])


In [12]:
# Getting all row for 1st column
print(x[:, 0])

# Getting all columns for 1st row
print(x[0, :])

# Getting element at 2nd row and 2nd col
print(x[1, 1])

tensor([0.5073, 0.2781, 0.6344, 0.8707, 0.4571])
tensor([0.5073, 0.3651, 0.7974])
tensor(0.3670)


If tensor has only 1 value, we can use **.item()** to get the actual value

In [13]:
print(x[1, 1])
print(x[1, 1].item())

tensor(0.3670)
0.36701613664627075


### Reshaping a tensor

In [14]:
x = torch.rand(4, 4)
print(x, x.shape)
y = x.view(16)
print(y, y.shape)

tensor([[0.1745, 0.1742, 0.5210, 0.3420],
        [0.9943, 0.2375, 0.1123, 0.6987],
        [0.6777, 0.6530, 0.5122, 0.3255],
        [0.6196, 0.5645, 0.9113, 0.2957]]) torch.Size([4, 4])
tensor([0.1745, 0.1742, 0.5210, 0.3420, 0.9943, 0.2375, 0.1123, 0.6987, 0.6777,
        0.6530, 0.5122, 0.3255, 0.6196, 0.5645, 0.9113, 0.2957]) torch.Size([16])


In [15]:
# Getting 8 columns and number of rows will manage themselves
y = x.view(-1, 8)
print(y, y.shape)

tensor([[0.1745, 0.1742, 0.5210, 0.3420, 0.9943, 0.2375, 0.1123, 0.6987],
        [0.6777, 0.6530, 0.5122, 0.3255, 0.6196, 0.5645, 0.9113, 0.2957]]) torch.Size([2, 8])


NumPy arrays require data to be in the CPU memory. So if the tenor from which array is being created is on GPU, it needs to be transferred to CPU first otherwise will lead to error

Then both the tensor and the array will share same memory address

In [16]:
### Conversion from numpy arrays
import torch
import numpy

device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print(device)

try:
    a = torch.ones(5)
    print(type(a), a)
    #a_CPU = a.cpu()
    b = a.numpy()
    print(type(b), (b))
    print("In try block1")

except Exception as e:
    print(e)

try:
    a = torch.ones(5).to(device)
    print(type(a), a)
    #a_CPU = a.cpu()
    b = a.numpy()
    print(type(b), (b))
    print("In try block2")

except Exception as e:
    print(e)

finally:
    print("*"*100)
    print("Corrected Version")
    a = torch.ones(5).to(device)
    print(type(a), a)
    # Transferred to CPU
    a_CPU = a.cpu()
    b = a_CPU.numpy()
    print(type(b), (b))

cuda
<class 'torch.Tensor'> tensor([1., 1., 1., 1., 1.])
<class 'numpy.ndarray'> [1. 1. 1. 1. 1.]
In try block1
<class 'torch.Tensor'> tensor([1., 1., 1., 1., 1.], device='cuda:0')
can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.
****************************************************************************************************
Corrected Version
<class 'torch.Tensor'> tensor([1., 1., 1., 1., 1.], device='cuda:0')
<class 'numpy.ndarray'> [1. 1. 1. 1. 1.]


Changing 1st wil affect the other

In [17]:
a_CPU.add_(1)
print(a_CPU)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [18]:
a = np.ones(5)
print(type(a), a)
b = torch.from_numpy(a)
print(type(b), b)

a = a+1 # Creates new instance of a
print(a)
print(b)

<class 'numpy.ndarray'> [1. 1. 1. 1. 1.]
<class 'torch.Tensor'> tensor([1., 1., 1., 1., 1.], dtype=torch.float64)
[2. 2. 2. 2. 2.]
tensor([1., 1., 1., 1., 1.], dtype=torch.float64)


Again, they are sharing same memory address

In [19]:
a = np.ones(5)
print(type(a), a)
b = torch.from_numpy(a)
print(type(b), b)

a+=1
print(a)
print(b)

<class 'numpy.ndarray'> [1. 1. 1. 1. 1.]
<class 'torch.Tensor'> tensor([1., 1., 1., 1., 1.], dtype=torch.float64)
[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
