In [1]:
import torch
import numpy as np

In [2]:
print(torch.cuda.is_available())

device = torch.device('cuda' if torch.cuda.is_available() else "cpu")
print(f"{device} is being used")

False
cpu is being used


### Creating Tensors

In [3]:
# Creating an empty tensor
x = torch.empty(size=(1, ))
print(x)
x = torch.empty(1)
print(x)
x = torch.empty(size=(2, 3))
print(x)

tensor([1.5624e-42])
tensor([-3.8462e-27])
tensor([[-3.8462e-27,  4.5003e-41,  1.1777e+11],
        [ 3.2432e-41,  1.1765e+11,  3.2432e-41]])


In [4]:
# Creating Random tensors
x = torch.rand(2, 2)
print(x)
x = torch.rand(size=(2, 2))
print(x)

tensor([[0.0067, 0.7214],
        [0.7283, 0.4512]])
tensor([[0.3046, 0.7079],
        [0.4182, 0.5045]])


In [5]:
# Tensord with 0s or 1s
x = torch.zeros(size=(2, 2), dtype=torch.int32)
print(f"x = {x}, Size =  {x.size()}")
x = torch.ones(size=(2, 2))
print(x)

x = tensor([[0, 0],
        [0, 0]], dtype=torch.int32), Size =  torch.Size([2, 2])
tensor([[1., 1.],
        [1., 1.]])


In [6]:
# Creating tensor from lists
x = torch.tensor([1,2,3,4])
print(x)

tensor([1, 2, 3, 4])


### Basic Tensor Operations

In [7]:
x = torch.rand(size=(2, 2))
y = torch.rand(size=(2, 2))
z = x+y
print(z)
z = torch.add(x, y)
print(z)

tensor([[1.5466, 0.5100],
        [0.5125, 1.0400]])
tensor([[1.5466, 0.5100],
        [0.5125, 1.0400]])


In [8]:
# Using inplace addition, y's value is changed to the sum
y.add_(x)
print(y)

tensor([[1.5466, 0.5100],
        [0.5125, 1.0400]])


In [9]:
# Element-wise multiplication
z = x*y
print(z)
z = torch.mul(x, y)
print(z)

tensor([[1.0594e+00, 2.1977e-05],
        [7.4438e-02, 6.3079e-01]])
tensor([[1.0594e+00, 2.1977e-05],
        [7.4438e-02, 6.3079e-01]])


In [10]:
# Element-wise Division
z = x/y
print(z)
z = torch.div(x, y)
print(z)

tensor([[4.4288e-01, 8.4503e-05],
        [2.8343e-01, 5.8322e-01]])
tensor([[4.4288e-01, 8.4503e-05],
        [2.8343e-01, 5.8322e-01]])


### Slicing operations

In [11]:
x = torch.rand(size=(5, 3))
print(x)

tensor([[0.7338, 0.1517, 0.4736],
        [0.1734, 0.0406, 0.5236],
        [0.0609, 0.2037, 0.3716],
        [0.4117, 0.7356, 0.7475],
        [0.1156, 0.8449, 0.6207]])


In [12]:
# Getting all row for 1st column
print(x[:, 0])

# Getting all columns for 1st row
print(x[0, :])

# Getting element at 2nd row and 2nd col
print(x[1, 1])

tensor([0.7338, 0.1734, 0.0609, 0.4117, 0.1156])
tensor([0.7338, 0.1517, 0.4736])
tensor(0.0406)


If tensor has only 1 value, we can use **.item()** to get the actual value

In [13]:
print(x[1, 1])
print(x[1, 1].item())

tensor(0.0406)
0.04056739807128906


### Reshaping a tensor

In [14]:
x = torch.rand(4, 4)
print(x, x.shape)
y = x.view(16)
print(y, y.shape)

tensor([[0.3925, 0.6364, 0.1015, 0.4229],
        [0.8701, 0.4657, 0.3012, 0.7458],
        [0.1402, 0.1434, 0.7225, 0.2014],
        [0.1011, 0.3525, 0.8415, 0.6462]]) torch.Size([4, 4])
tensor([0.3925, 0.6364, 0.1015, 0.4229, 0.8701, 0.4657, 0.3012, 0.7458, 0.1402,
        0.1434, 0.7225, 0.2014, 0.1011, 0.3525, 0.8415, 0.6462]) torch.Size([16])


In [15]:
# Getting 8 columns and number of rows willl manage themselves
y = x.view(-1, 8)
print(y, y.shape)

tensor([[0.3925, 0.6364, 0.1015, 0.4229, 0.8701, 0.4657, 0.3012, 0.7458],
        [0.1402, 0.1434, 0.7225, 0.2014, 0.1011, 0.3525, 0.8415, 0.6462]]) torch.Size([2, 8])


NumPy arrays require data to be in the CPU memory. So if the tenor from which array is being created is on GPU, it needs to be transferred to CPU first.

Then both the tensor and the array will share same memory address

In [16]:
### Conversion from numpy arrays

a = torch.ones(5).to(device)
print(type(a), a)
a_CPU = a.cpu()
b = a_CPU.numpy()
print(type(b), (b))

<class 'torch.Tensor'> tensor([1., 1., 1., 1., 1.])
<class 'numpy.ndarray'> [1. 1. 1. 1. 1.]


Changing 1st wil affect the other

In [17]:
a_CPU.add_(1)
print(a_CPU)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [18]:
a = np.ones(5)
print(type(a), a)
b = torch.from_numpy(a)
print(type(b), b)

a = a+1 # Creates new instance of a
print(a)
print(b)

<class 'numpy.ndarray'> [1. 1. 1. 1. 1.]
<class 'torch.Tensor'> tensor([1., 1., 1., 1., 1.], dtype=torch.float64)
[2. 2. 2. 2. 2.]
tensor([1., 1., 1., 1., 1.], dtype=torch.float64)


Again, they are sharing same memory address

In [19]:
a = np.ones(5)
print(type(a), a)
b = torch.from_numpy(a)
print(type(b), b)

a+=1
print(a)
print(b)

<class 'numpy.ndarray'> [1. 1. 1. 1. 1.]
<class 'torch.Tensor'> tensor([1., 1., 1., 1., 1.], dtype=torch.float64)
[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
